def generate_pull_request(
    task: str,
    plan: str,
    review: str
):

    title = (
        task.strip()
            .splitlines()[0]
            [:80]
    )

    return f"""
# Pull Request

## Title

{title}

## Task

{task}

## Implementation Summary

{plan}

## Review Summary

{review}

## Checklist

- [x] Code Generated
- [x] Review Completed
- [x] Approval Requested

## Notes

Generated by Atlas.
"""